[package]
name = "beautiful-contract-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.beautiful-contract]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.50.0"
default-features = false
